import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <a href="http://127.0.0.1:5000/">Click here to start</a>
        <a href="http://127.0.0.1:5000/sign_out">Sign Out</a>
        <Link href='/trends'>
          <button>Trends</button>
        </Link>
      </main>
    </>
  )
}
