import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Login() {

  const handleStartClick = async () => {
    const response = await fetch('http://0.0.0.0:5001/');
    const data = await response.json();
    console.log(data)
    window.location.href = data;
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <a onClick={handleStartClick}>Click here to start</a>
        <a href="http://localhost:5001/sign_out">Sign Out</a>
        <Link href='/home'>
          <button>Trends</button>
        </Link>
      </main>
    </>
  )
}
