import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Trends() {

    type Playlist = {
        id: string;
        name: string;
        // other playlist properties
    }

    const [wrappedPlaylists, setWrappedPlaylists] = useState<Playlist[]>([])
    const [accessToken, setAccessToken] = useState('');

    const clearQueryParams = () => {
        const newUrl = window.location.pathname;
        window.history.replaceState({}, '', newUrl);
      };
      
    useEffect(() => {

        const queryString = window.location.search;
        const urlParams = new URLSearchParams(queryString);
        const accessToken = urlParams.get('access_token');
        // setAccessToken(accessToken)
        const refreshToken = urlParams.get('refresh_token');
        // window.history.pushState({}, '', window.location.pathname);
    
        // console.log(accessToken);
        // console.log(refreshToken);

        async function fetchWrappedPlaylists() {
            console.log('HELLLLOOOO')
            console.log(accessToken)
            const res = await fetch('http://127.0.0.1:5000/wrapped_playlists', {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${accessToken}`
                  },
            })
            const data = await res.json()
            setWrappedPlaylists(data)
        }
        fetchWrappedPlaylists();
        // clearQueryParams();
    }, [])


    return (
        <>
            <Head>
                <title>Trends</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div>
                    <h1>Wrapped Playlists</h1>
                    <ul>
                        {wrappedPlaylists.map(playlist => (
                            <li key={playlist.id}>{playlist.name}</li>
                        ))}
                    </ul>
                </div>
            </main>
        </>
    )
}


